const images=import.meta.glob('../assets/foodImages/fud*.png',{
  eager:true,
  as:'url',
});


function getImageById(id){
  return images[`../assets/foodImages/fud${id}.png`];
}

const Products = [
  {
    id: 1,
    name: 'Shawarmer',
    description:'Street Food,Shawarmas,Rolls...',
    location:'Irinjalakuda',
    category: 'Electronics',
    time:'20-25 mins',
    rating: 4.5,
    image: getImageById(1),
  },
  {
    id: 2,
    name: 'Paradise Family Restaurant',
    description:'North Indian,South Indian,Biriyani,...',
    location:'Chalakudy',
    category: 'Women',
    time:'40-45 mins',
    rating: 4.8,
    image: getImageById(2),
  },
  {
    id: 3,
    name: 'Jalaram Foods N Ice Cream',
    description:'bakery,Icecreams,CoolDrinks,...',
    location:'Parasia Road',
    category: 'Electronics',
    time:'30-35 mins',
    rating: 3.9,
    image: getImageById(3),
  },
  {
    id: 4,
    name: 'The Burger House',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Parasia Road',
    category: 'Electronics',
    time:'30-35 mins',
    rating: 4.3,
    image: getImageById(4),
  },
  {
    id: 5,
    name: 'Spice Club',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Parasia Road',
    category: 'Women',
    time:'50-55 mins',
    rating: 4.6,
    image: getImageById(5),
  },
  {
    id: 6,
    name: 'Art Cafe',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Irinjalakuda',
    category: 'Gents',
    time:'15-20 mins',
    rating: 3.0,
    image: getImageById(6),
  },
  {
    id: 7,
    name: 'Indian Cofee House',
    description:'Chaat,Beverages,Snacks,...',
    location:'Parasia Road',
    category: 'Women',
    time:'20-35 mins',
    rating: 3.5,
    image: getImageById(7),
  },
  {
    id: 8,
    name: 'Asha Hotel',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Irinjalakuda',
    category: 'Gents',
    time:'20-35 mins',
    rating: 4.0,
    image: getImageById(8),
  },
  {
    id: 9,
    name: 'Jalaram Foods N Ice Cream',
     description:'bakery,Icecreams,CoolDrinks,...',
    location:'Chalakudy',
    category: 'Electronics',
    time:'50-55 mins',
    rating: 4.5,
    image: getImageById(9),
  },
  {
    id: 10,
    name: 'Magic Momo',
     description:'Momos,Chineese,...',
    location:'Parasia Road',
    category: 'Women',
    time:'40-45 mins',
    rating: 4.8,
    image: getImageById(10),
  },
  {
    id: 11,
    name: 'Pizza Hut',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Parasia Road',
    category: 'Electronics',
    time:'30-35 mins',
    rating: 3.9,
    image: getImageById(11),
  },
  {
    id: 12,
    name: 'Dil Se Dabeli',
     description:'Street Food,Chinese,Snacks,...',
    location:'Chalakudy',
    category: 'Electronics',
    time:'40-45 mins',
    rating: 4.3,
    image: getImageById(12),
  },
  {
    id: 13,
    name: 'Art Cafe',
     description:'Street Food,Chinese,Snacks,...',
    location:'Irinjalakuda',
    category: 'Women',
    time:'20-25 mins',
    rating: 4.6,
    image: getImageById(13),
  },
  {
    id: 14,
    name: 'Pizza Hut',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Irinjalakuda',
    category: 'Gents',
    time:'50-55 mins',
    rating: 3.0,
    image: getImageById(14),
  },
  {
    id: 15,
    name: 'Royal Kitchen',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Parasia Road',
    category: 'Women',
    time:'30-35 mins',
    rating: 3.5,
    image: getImageById(15),
  },
  {
    id: 16,
    name: 'Hotel Neelima',
     description:'Street Food,Shawarmas,Rolls..',
    location:'Parasia Road',
    category: 'Gents',
    time:'20-35 mins',
    rating: 4.0,
    image: getImageById(16),
  },
  {
    id: 17,
    name: 'Paradise Family Restaurant',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Chalakudy',
    category: 'Electronics',
    time:'50-55 mins',
    rating: 4.5,
    image: getImageById(17),
  },
  {
    id: 18,
    name: 'Dil Se Dabeli',
     description:'Street Food,Chinese,Snacks,...',
    location:'Parasia Road',
    category: 'Women',
    time:'40-45 mins',
    rating: 4.8,
    image: getImageById(18),
  },
  {
    id: 19,
    name: 'Bakery World',
     description:'bakery,Icecreams,Snacks,...',
    location:'Parasia Road',
    category: 'Electronics',
    time:'50-55 mins',
    rating: 3.9,
    image: getImageById(19),
  },
  {
    id: 20,
    name: 'The Woods cafe',
     description:'Chaat,Beverages,Snacks,...',
    location:'Irinjalakuda',
    category: 'Electronics',
    time:'50-55 mins',
    rating: 4.3,
    image: getImageById(20),
  },

];

export default Products;