const images=import.meta.glob('../assets/foodImages/fud*.png',{
  eager:true,
  as:'url',
});


function getImageById(id){
  return images[`../assets/foodImages/fud${id}.png`];
}

const Products = [
  {
    id: 1,
    hotelName: 'Shawarmer',
    fudname:'Shawarma Roll',
    price: 110,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
    description:'Street Food,Shawarmas,Rolls...',
    location:'Irinjalakuda',
    category: 'Non-Veg',
    time:'20-25 mins',
    rating: 4.5,
    image: getImageById(1),
  },
  {
    id: 2,
    hotelName: 'Paradise Family Restaurant',
    fudname:'Paneer Tikka',
    price: 160,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
    description:'North Indian,South Indian,Biriyani,...',
    location:'Chalakudy',
    category: 'Pure-Veg',
    time:'40-45 mins',
    rating: 4.8,
    image: getImageById(2),
  },
  {
    id: 3,
    hotelName: 'Jalaram Foods N Ice Cream',
    fudname:'Strawberry Icecream',
    price: 149,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
    description:'bakery,Icecreams,CoolDrinks,...',
    location:'Parasia Road',
    category: 'Desserts',
    time:'30-35 mins',
    rating: 3.9,
    image: getImageById(3),
  },
  {
    id: 4,
    hotelName: 'The Burger House',
    fudname:'Chicken Crispy Burger',
    price: 180,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Parasia Road',
    category: 'Non-Veg',
    time:'30-35 mins',
    rating: 4.3,
    image: getImageById(4),
  },
  {
    id: 5,
    hotelName: 'Spice Club',
    fudname:'Puri Masala',
    price: 120,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Parasia Road',
    category: 'Pure-Veg',
    time:'50-55 mins',
    rating: 4.6,
    image: getImageById(5),
  },
  {
    id: 6,
    hotelName: 'Art Cafe',
    fudname:'Margherita',
    price: 310,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Irinjalakuda',
    category: 'Non-Veg',
    time:'15-20 mins',
    rating: 3.0,
    image: getImageById(6),
  },
  {
    id: 7,
    hotelName: 'Indian Cofee House',
    fudname:'Cofee',
    price: 40,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
    description:'Chaat,Beverages,Snacks,...',
    location:'Parasia Road',
    category: 'Drinks',
    time:'20-35 mins',
    rating: 3.5,
    image: getImageById(7),
  },
  {
    id: 8,
    hotelName: 'Asha Hotel',
    fudname:'Cheese Paneer Masala Curry',
    price: 140,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Irinjalakuda',
    category: 'Pure-Veg',
    time:'20-35 mins',
    rating: 4.0,
    image: getImageById(8),
  },
  {
    id: 9,
    hotelName: 'Jalaram Foods N Ice Cream',
    fudname:'Malai Kulfi Icecream',
    price: 50,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'bakery,Icecreams,CoolDrinks,...',
    location:'Chalakudy',
    category: 'Desserts',
    time:'50-55 mins',
    rating: 4.5,
    image: getImageById(9),
  },
  {
    id: 10,
    hotelName: 'Magic Momo',
    fudname:'Chicken Momos',
    price: 190,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'Momos,Chineese,...',
    location:'Parasia Road',
    category: 'Non-Veg',
    time:'40-45 mins',
    rating: 4.8,
    image: getImageById(10),
  },
  {
    id: 11,
    hotelName: 'Pizza Hut',
    fudname:'Non-veg Pizza',
    price: 260,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Parasia Road',
    category: 'Non-Veg',
    time:'30-35 mins',
    rating: 3.9,
    image: getImageById(11),
  },
  {
    id: 12,
    hotelName: 'Dil Se Dabeli',
    fudname:'Pav Bhaji',
    price: 220,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'Street Food,Chinese,Snacks,...',
    location:'Chalakudy',
    category: 'Pure-Veg',
    time:'40-45 mins',
    rating: 4.3,
    image: getImageById(12),
  },
  {
    id: 13,
    hotelName: 'Art Cafe',
    fudname:'Salad',
    price: 110,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'Street Food,Chinese,Snacks,...',
    location:'Irinjalakuda',
    category: 'Pure-Veg',
    time:'20-25 mins',
    rating: 4.6,
    image: getImageById(13),
  },
  {
    id: 14,
    hotelName: 'Pizza Hut',
    fudname:'Cheese Pizza',
    price: 200,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'South Indian,Snacks,Pizzas,Burgers..',
    location:'Irinjalakuda',
    category: 'Non-Veg',
    time:'50-55 mins',
    rating: 3.0,
    image: getImageById(14),
  },
  {
    id: 15,
    hotelName: 'Royal Kitchen',
    fudname:'Chicken Biriyani',
    price: 170,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Parasia Road',
    category: 'Non-Veg',
    time:'30-35 mins',
    rating: 3.5,
    image: getImageById(15),
  },
  {
    id: 16,
    hotelName: 'Hotel Neelima',
    fudname:'Chineese Nuddles',
    price: 110,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'Street Food,Shawarmas,Rolls..',
    location:'Parasia Road',
    category: 'Pure-Veg',
    time:'20-35 mins',
    rating: 4.0,
    image: getImageById(16),
  },
  {
    id: 17,
    hotelName: 'Paradise Family Restaurant',
    fudname:'Paneer Butter Curry',
    price: 160,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'North Indian,South Indian,Biriyani,...',
    location:'Chalakudy',
    category: 'Pure-Veg',
    time:'50-55 mins',
    rating: 4.5,
    image: getImageById(17),
  },
  {
    id: 18,
    hotelName: 'Royal Kitchen',
    fudname:'Muttan Biriyani',
    price: 310,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'Street Food,Chinese,Snacks,...',
    location:'Parasia Road',
    category: 'Non-Veg',
    time:'40-45 mins',
    rating: 4.8,
    image: getImageById(18),
  },
  {
    id: 19,
    hotelName: 'Bakery World',
    fudname:'Black Forest Cake',
    price: 550,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'bakery,Icecreams,Snacks,...',
    location:'Parasia Road',
    category: 'Dessert',
    time:'50-55 mins',
    rating: 3.9,
    image: getImageById(19),
  },
  {
    id: 20,
    hotelName: 'The Woods cafe',
    fudname:'Masala Tea',
    price: 40,
    fudDescription:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nesciunt fuga praesentium vero nemo',
     description:'Chaat,Beverages,Snacks,...',
    location:'Irinjalakuda',
    category: 'Drinks',
    time:'50-55 mins',
    rating: 4.3,
    image: getImageById(20),
  },

];

export default Products;